changes from WM to MD
aaru-dps/Aaru.Documentation pull request #4
Opened 2020-03-16 20:13 UTC by PhynixHeart

2020-03-17 17:57 UTC, jonasrosland requested changes
Great stuff, thank you @PhynixHeart !

Few things to change, and can you please remove the footnote markers from:
- Media-dump-formats-supported-by-Aaru.md
- Reporting-physical-device-capabilities.md

We also have a merge conflict with the README file, I'll help you sort that out.

2020-03-17 17:57 UTC, jonasrosland commented on 5.0/List-files.md
> +```Aaru -d [true/false] -v [true/false] filesystem list -h [true/false] -e [encoding] -l [true/false]```
Could you please make changes to the docs so that the command examples uses lowercase `aaru` instead of `Aaru`?

2020-03-17 17:57 UTC, jonasrosland commented on 5.0/List-files.md
> +```Aaru filesystem list -l -e x-mac-icelandic mydisc.cue```
Same thing here, make sure it says `aaru`

2020-03-23 19:13 UTC, claunia approved these changes

2020-03-23 19:13 UTC, merged